steps:
  - name: golang
    entrypoint: /bin/bash
    args: 
      - -c
      - make build_all
    env:
      - 'VERSION=0.1'
artifacts:
  objects:
    location: 'gs://kasa-stocks/'
    paths: ['bin/darwin_amd64/kasa-stocks_${VERSION}','bin/darwin_amd64/kasa-stocks_${VERSION}_sha256.txt']
    location: 'gs://kasa-stocks/'
    paths: ['bin/darwin_arm64/kasa-stocks_${VERSION}','bin/darwin_arm64/kasa-stocks_${VERSION}_sha256.txt']